source: content
destination: dist
collections:
  publications:
    output: true
    sort_by: date
  events:
    output: true
keep_files:
  - status.js
  - navigation.js
  - home.js
  - main.css
  - getStarted.js
encoding: utf-8
