title: FiQCI
author: The FiQCI Consortium
logo: assets/images/FiQCI-logo.png
favicon: assets/images/favicon.png
description: >-
  Web presence of the Finnish Quantum-Computing Infrastructure. We provide state-of-the-art quantum-computing services to Finnish RDI communities.
header_pages:
  - pages/access.md
  - pages/publications.md
  - pages/about.md
  - pages/status.md
  - pages/events.md
excerpt_max_length: 250
