name: CI - Build and test
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.253.0
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.10.0'
          cache: 'npm'

      - name: Install Node.js packages
        run: npm ci

      - name: Build stylesheets using Tailwind CSS
        run: npm run-script tailwindcss -- --minify

      - name: Build React components using Webpack
        env:
          MATOMO_URL: mwa-acf.2.rahtiapp.fi
          MATOMO_TAG_MANAGER_CONTAINER: jyLY2YKH
        run: npm run-script webpack -- --mode=production

      - name: Build site using Jekyll
        env:
          JEKYLL_ENV: production
        run: npm run-script jekyll:build

      - name: Check build artifacts
        run: |
          ls -la dist/
          echo "Build completed successfully!"
