name: Build and deploy site to GitHub Pages
on:
  push:
    branches: [ "new-fiqci" ]
  pull_request:
    branches: [ "new-fiqci" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: new-fiqci

      - name: Install Ruby and Node.js using asdf
        uses: asdf-vm/actions/install@v3.0.2

      - name: Install Ruby gems
        run: bundle install

      - name: Install Node.js packages
        run: npm install

      - name: Build stylesheets using Tailwind CSS
        run: npm run-script tailwindcss -- --minify

      - name: Build React components using Webpack
        env:
          MATOMO_URL: mwa-acf.2.rahtiapp.fi
          MATOMO_TAG_MANAGER_CONTAINER: jyLY2YKH
        run: npm run-script webpack -- --mode=production

      - name: Build site using Jekyll
        env:
          JEKYLL_ENV: production
        run: npm run-script jekyll:build

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
